version: '3.7'

services:
  web:
    restart: always
    image: ${IMAGE_NAME:? is not set or is empty}:${IMAGE_VERSION}
    env_file:
      - ./.env
      - ./../.env
    ports:
      - "${EXPOSED_PORT}:80"
